/**
 * Reading comprehension.
 *
 * The reading session measures decoding; this module measures understanding.
 * It produces two activities from a passage the child has just read:
 *
 *  1. Multiple-choice questions across the three question types elementary
 *     teachers use — literal ("right there"), inferential ("think and search")
 *     and vocabulary-in-context.
 *  2. An oral retell, scored by how many of the passage's key ideas the child
 *     mentioned in their own words.
 *
 * Questions are generated by the backend AI proxy, but the module always
 * degrades to a deterministic offline generator so a child on a bad connection
 * (or over quota) still gets a comprehension activity.
 */

import { z } from 'zod';
import { apiPost } from './apiClient';
import { gradeIndex, type GradeCode } from '../types/grade';

export type QuestionKind = 'literal' | 'inferential' | 'vocabulary';

export interface ComprehensionQuestion {
  id: string;
  kind: QuestionKind;
  prompt: string;
  /** Answer options; exactly one is correct. */
  choices: string[];
  /** Index into `choices`. */
  answerIndex: number;
  /** Shown after answering, right or wrong. */
  explanation: string;
}

export interface ComprehensionSet {
  questions: ComprehensionQuestion[];
  /** Key ideas used to score an oral retell. */
  keyIdeas: string[];
  /** True when the questions came from the offline generator. */
  offline: boolean;
}

export const QUESTION_KIND_META: Record<QuestionKind, { label: string; emoji: string; hint: string }> = {
  literal: { label: 'Right there', emoji: '🔍', hint: 'The answer is written in the story.' },
  inferential: { label: 'Think about it', emoji: '🤔', hint: 'Put clues together to work it out.' },
  vocabulary: { label: 'Word meaning', emoji: '📖', hint: 'Use the sentence around the word.' },
};

const QuestionSchema = z.object({
  kind: z.enum(['literal', 'inferential', 'vocabulary']),
  prompt: z.string().min(1),
  choices: z.array(z.string().min(1)).min(2).max(4),
  answerIndex: z.number().int().nonnegative(),
  explanation: z.string().default(''),
});

const ResponseSchema = z.object({
  questions: z.array(QuestionSchema).min(1),
  keyIdeas: z.array(z.string().min(1)).default([]),
});

/** Younger readers get fewer questions and simpler wording. */
export function questionCountForGrade(grade: GradeCode): number {
  return gradeIndex(grade) <= 1 ? 3 : 4;
}

function systemPrompt(grade: GradeCode, count: number): string {
  const young = gradeIndex(grade) <= 1;
  return [
    `You write reading-comprehension checks for a grade ${grade} child (ages ${young ? '5-7' : '8-11'}).`,
    `Produce exactly ${count} multiple-choice questions about the passage the user gives you.`,
    young
      ? 'Use very short sentences and words a beginning reader knows. Three answer choices each.'
      : 'Include at least one "inferential" question that requires combining clues, and one "vocabulary" question about a word used in the passage. Four answer choices each.',
    'Every question must be answerable from the passage alone. Wrong choices must be plausible but clearly wrong to a careful reader.',
    'Also return 3-5 "keyIdeas": the short factual beats a child should mention when retelling the passage.',
    'Return ONLY JSON: {"questions":[{"kind":"literal"|"inferential"|"vocabulary","prompt":string,"choices":string[],"answerIndex":number,"explanation":string}],"keyIdeas":string[]}',
    'No markdown fences, no commentary.',
  ].join(' ');
}

function stripFences(content: string): string {
  return content.replace(/```json?\n?/g, '').replace(/```/g, '').trim();
}

function normalise(raw: z.infer<typeof ResponseSchema>): ComprehensionQuestion[] {
  return raw.questions
    .filter((q) => q.answerIndex < q.choices.length)
    .map((q, index) => ({
      id: `cq_${index}`,
      kind: q.kind,
      prompt: q.prompt.trim(),
      choices: q.choices.map((c) => c.trim()),
      answerIndex: q.answerIndex,
      explanation: q.explanation.trim() || QUESTION_KIND_META[q.kind].hint,
    }));
}

/**
 * Generate a comprehension set for a passage.
 *
 * Never rejects: any failure (quota, network, malformed model output) falls
 * back to {@link buildOfflineComprehension}.
 */
export async function generateComprehension(
  text: string,
  grade: GradeCode,
): Promise<ComprehensionSet> {
  const passage = text.replace(/\s+/g, ' ').trim();
  if (!passage) return { questions: [], keyIdeas: [], offline: true };

  const count = questionCountForGrade(grade);

  try {
    const data = await apiPost<unknown, { content: string }>('/openai/chat', {
      purpose: 'learning-activity',
      messages: [
        { role: 'system', content: systemPrompt(grade, count) },
        { role: 'user', content: `Passage: "${passage}"` },
      ],
      temperature: 0.4,
      max_tokens: 900,
      response_format: 'json_object',
    });

    const parsed = ResponseSchema.safeParse(JSON.parse(stripFences(data.content ?? '')));
    if (parsed.success) {
      const questions = normalise(parsed.data);
      if (questions.length > 0) {
        return {
          questions,
          keyIdeas: parsed.data.keyIdeas.length > 0 ? parsed.data.keyIdeas : extractKeyIdeas(passage),
          offline: false,
        };
      }
    }
  } catch { /* fall through to the offline generator */ }

  return buildOfflineComprehension(passage, grade);
}

// ---------------------------------------------------------------------------
// Offline generator
// ---------------------------------------------------------------------------

export function splitSentences(text: string): string[] {
  return text
    .replace(/\s+/g, ' ')
    .split(/(?<=[.!?])\s+/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

const STOP_WORDS = new Set([
  'the', 'a', 'an', 'and', 'or', 'but', 'if', 'then', 'so', 'to', 'of', 'in', 'on', 'at', 'for',
  'with', 'is', 'was', 'are', 'were', 'be', 'been', 'it', 'its', 'this', 'that', 'these', 'those',
  'i', 'you', 'he', 'she', 'they', 'we', 'my', 'his', 'her', 'their', 'our', 'him', 'them', 'us',
  'had', 'has', 'have', 'did', 'do', 'does', 'not', 'as', 'up', 'down', 'out', 'from', 'by', 'me',
  'all', 'can', 'will', 'just', 'very', 'too', 'there', 'here', 'when', 'what', 'who', 'how',
]);

/** Content words in the passage, most distinctive first. */
export function contentWords(text: string): string[] {
  const counts = new Map<string, number>();
  for (const raw of text.toLowerCase().match(/[a-z']+/g) ?? []) {
    const word = raw.replace(/^'+|'+$/g, '');
    if (word.length < 4 || STOP_WORDS.has(word)) continue;
    counts.set(word, (counts.get(word) ?? 0) + 1);
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || b[0].length - a[0].length || a[0].localeCompare(b[0]))
    .map(([word]) => word);
}

/** The passage's opening beats, used as retell targets when AI is unavailable. */
export function extractKeyIdeas(text: string, max = 4): string[] {
  return splitSentences(text).slice(0, max);
}

/**
 * Deterministic comprehension questions built from the passage itself.
 *
 * These are genuinely answerable — "which sentence is in the story?",
 * "which word appears most?", "what happens first?" — so the activity still
 * exercises attention to text even without the model.
 */
export function buildOfflineComprehension(text: string, grade: GradeCode): ComprehensionSet {
  const passage = text.replace(/\s+/g, ' ').trim();
  const sentences = splitSentences(passage);
  const words = contentWords(passage);
  const questions: ComprehensionQuestion[] = [];

  if (sentences.length >= 2) {
    const distractor = `${sentences[sentences.length - 1].replace(/[.!?]$/, '')} instead of anything else.`;
    questions.push({
      id: 'cq_offline_first',
      kind: 'literal',
      prompt: 'Which sentence comes first in the story?',
      choices: [sentences[0], sentences[1], distractor].slice(0, 3),
      answerIndex: 0,
      explanation: 'Look back at the very beginning of the passage.',
    });
  }

  if (words.length >= 3) {
    questions.push({
      id: 'cq_offline_topic',
      kind: 'inferential',
      prompt: 'Which word tells you the most about what this story is about?',
      choices: [words[0], words[1], words[2]],
      answerIndex: 0,
      explanation: `"${words[0]}" shows up more than the others, so the story keeps coming back to it.`,
    });
  }

  const target = words[0];
  if (target) {
    const containing = sentences.find((s) => s.toLowerCase().includes(target));
    if (containing) {
      const others = sentences.filter((s) => s !== containing).slice(0, 2);
      questions.push({
        id: 'cq_offline_vocab',
        kind: 'vocabulary',
        prompt: `Which sentence uses the word "${target}"?`,
        choices: [containing, ...others].slice(0, 3),
        answerIndex: 0,
        explanation: `Find "${target}" by scanning each sentence.`,
      });
    }
  }

  return {
    questions: questions.slice(0, questionCountForGrade(grade)),
    keyIdeas: extractKeyIdeas(passage),
    offline: true,
  };
}

// ---------------------------------------------------------------------------
// Oral retell scoring
// ---------------------------------------------------------------------------

export interface RetellScore {
  /** Percentage of key ideas the retell covered, 0–100. */
  coverage: number;
  /** Key ideas the child mentioned. */
  covered: string[];
  /** Key ideas still missing. */
  missed: string[];
  /** Number of words the child said. */
  wordCount: number;
  label: string;
  message: string;
}

/** Share of an idea's content words that must appear for it to count as covered. */
const IDEA_MATCH_RATIO = 0.4;

/**
 * Score a spoken retell against the passage's key ideas.
 *
 * Matching is deliberately generous — content-word overlap, not wording — so a
 * child who retells the story in their own words gets credit, which is the
 * whole point of a retell.
 */
export function scoreRetell(retell: string, keyIdeas: string[]): RetellScore {
  const said = new Set(contentWords(retell));
  const wordCount = (retell.trim().match(/\S+/g) ?? []).length;

  const covered: string[] = [];
  const missed: string[] = [];

  for (const idea of keyIdeas) {
    const ideaWords = contentWords(idea);
    if (ideaWords.length === 0) continue;
    const hits = ideaWords.filter((word) => said.has(word)).length;
    if (hits / ideaWords.length >= IDEA_MATCH_RATIO) covered.push(idea);
    else missed.push(idea);
  }

  const scorable = covered.length + missed.length;
  const coverage = scorable === 0 ? 0 : Math.round((covered.length / scorable) * 100);

  let label: string;
  let message: string;
  if (coverage >= 80) {
    label = 'Great retelling!';
    message = 'You remembered almost the whole story in your own words.';
  } else if (coverage >= 50) {
    label = 'Good retelling';
    message = 'You got the main parts. Look back for the bits you missed.';
  } else if (wordCount === 0) {
    label = 'Nothing recorded';
    message = 'Tap the microphone and tell the story in your own words.';
  } else {
    label = 'Keep going';
    message = 'Try again and add what happened next.';
  }

  return { coverage, covered, missed, wordCount, label, message };
}

/** Percentage score for a completed question set. */
export function scoreComprehension(
  questions: ComprehensionQuestion[],
  answers: Record<string, number>,
): { correct: number; total: number; percent: number } {
  const total = questions.length;
  const correct = questions.filter((q) => answers[q.id] === q.answerIndex).length;
  return { correct, total, percent: total === 0 ? 0 : Math.round((correct / total) * 100) };
}
