/**
 * Pre-generated immersive moments for demo paragraphs.
 * Generated by scripts/generateMomentCache.mjs -- do not edit manually.
 */

import type { KeyMoment } from '../services/momentsService';

/** Key format: "{grade}-{paragraphIndex}" e.g. "K-0", "3-2", "6-1" */
export const momentCache: Record<string, KeyMoment[]> = {
  "K-0": [
    {
      "wordIndex": 1,
      "triggerWord": "cat",
      "type": "image",
      "imageQuery": "Cat",
      "musicCategory": "",
      "caption": "Cats are playful and love to nap!"
    },
    {
      "wordIndex": 9,
      "triggerWord": "big.",
      "type": "music",
      "imageQuery": "",
      "musicCategory": "adventure",
      "caption": "Big adventures await when you explore the world!"
    },
    {
      "wordIndex": 13,
      "triggerWord": "red.",
      "type": "both",
      "imageQuery": "Red_cat",
      "musicCategory": "celebration",
      "caption": "Red cats are unique and often loved for their color!"
    }
  ],
  "K-1": [
    {
      "wordIndex": 3,
      "triggerWord": "dog.",
      "type": "image",
      "imageQuery": "Dog",
      "musicCategory": "",
      "caption": "Dogs are known as man's best friend!"
    },
    {
      "wordIndex": 6,
      "triggerWord": "can",
      "type": "music",
      "imageQuery": "",
      "musicCategory": "adventure",
      "caption": "Adventures with dogs are always fun and exciting!"
    },
    {
      "wordIndex": 12,
      "triggerWord": "love",
      "type": "both",
      "imageQuery": "Love",
      "musicCategory": "peaceful",
      "caption": "Love makes the world a happier place!"
    }
  ],
  "K-2": [
    {
      "wordIndex": 1,
      "triggerWord": "sun",
      "type": "both",
      "imageQuery": "Sun",
      "musicCategory": "peaceful",
      "caption": "The sun is a giant ball of hot gases in the sky!"
    },
    {
      "wordIndex": 16,
      "triggerWord": "fun",
      "type": "music",
      "musicCategory": "celebration",
      "caption": "Fun days are perfect for playing outside and enjoying life!"
    }
  ],
  "1-0": [
    {
      "wordIndex": 4,
      "triggerWord": "park",
      "type": "image",
      "imageQuery": "City_park",
      "caption": "Parks are great places to play and enjoy nature!"
    },
    {
      "wordIndex": 12,
      "triggerWord": "swings.",
      "type": "both",
      "imageQuery": "Swing_set",
      "musicCategory": "celebration",
      "caption": "Swings let you soar high in the air like a bird!"
    },
    {
      "wordIndex": 17,
      "triggerWord": "slide.",
      "type": "image",
      "imageQuery": "Slide_(playground)",
      "caption": "Slides are super fun and can be really fast!"
    }
  ],
  "1-1": [
    {
      "wordIndex": 4,
      "triggerWord": "fish.",
      "type": "image",
      "imageQuery": "Goldfish",
      "caption": "Goldfish can come in many bright colors, including blue!"
    },
    {
      "wordIndex": 11,
      "triggerWord": "swims",
      "type": "music",
      "musicCategory": "peaceful",
      "caption": "Listening to water sounds can make you feel like you're underwater!"
    },
    {
      "wordIndex": 14,
      "triggerWord": "tank.",
      "type": "image",
      "imageQuery": "Fish_tank",
      "caption": "Fish tanks can be decorated with plants and colorful stones!"
    },
    {
      "wordIndex": 17,
      "triggerWord": "it",
      "type": "both",
      "imageQuery": "Feeding_fish",
      "musicCategory": "nature",
      "caption": "Fish love to eat, and they can be very playful during feeding time!"
    }
  ],
  "1-2": [
    {
      "wordIndex": 2,
      "triggerWord": "raining",
      "type": "both",
      "imageQuery": "Rain",
      "musicCategory": "nature",
      "caption": "Raindrops are tiny water droplets that fall from clouds!"
    },
    {
      "wordIndex": 8,
      "triggerWord": "rain",
      "type": "image",
      "imageQuery": "Rain",
      "musicCategory": "",
      "caption": "Rain helps plants grow and keeps our Earth green!"
    },
    {
      "wordIndex": 19,
      "triggerWord": "warm",
      "type": "music",
      "imageQuery": "",
      "musicCategory": "peaceful",
      "caption": "Warm milk can be cozy and comforting on rainy days!"
    }
  ],
  "2-0": [
    {
      "wordIndex": 6,
      "triggerWord": "farm.",
      "type": "image",
      "imageQuery": "Farm",
      "caption": "Farms are full of fun animals and fresh food!"
    },
    {
      "wordIndex": 19,
      "triggerWord": "baby",
      "type": "both",
      "imageQuery": "Goat",
      "musicCategory": "peaceful",
      "caption": "Baby goats are playful and love to jump around!"
    },
    {
      "wordIndex": 23,
      "triggerWord": "soft",
      "type": "music",
      "musicCategory": "peaceful",
      "caption": "Soft sounds can make you feel calm and happy!"
    }
  ],
  "2-1": [
    {
      "wordIndex": 3,
      "triggerWord": "birthday.",
      "type": "image",
      "imageQuery": "Birthday_party",
      "caption": "Birthday parties are filled with fun, friends, and cake!"
    },
    {
      "wordIndex": 6,
      "triggerWord": "seven",
      "type": "music",
      "musicCategory": "celebration",
      "caption": "Celebrating your seventh birthday is a big milestone!"
    },
    {
      "wordIndex": 17,
      "triggerWord": "cake",
      "type": "both",
      "imageQuery": "Cake",
      "musicCategory": "celebration",
      "caption": "Cake comes in many flavors and is a party favorite!"
    },
    {
      "wordIndex": 21,
      "triggerWord": "outside.",
      "type": "music",
      "musicCategory": "nature",
      "caption": "Playing outside is a great way to enjoy the sunshine!"
    }
  ],
  "2-2": [
    {
      "wordIndex": 18,
      "triggerWord": "dinosaurs.",
      "type": "image",
      "imageQuery": "Dinosaurs",
      "musicCategory": "adventure",
      "caption": "Dinosaurs roamed the Earth millions of years ago!"
    },
    {
      "wordIndex": 24,
      "triggerWord": "fly?",
      "type": "both",
      "imageQuery": "Pterosaurs",
      "musicCategory": "mysterious",
      "caption": "Some flying reptiles weren’t dinosaurs but lived alongside them!"
    }
  ],
  "3-0": [
    {
      "wordIndex": 6,
      "triggerWord": "Earth",
      "type": "image",
      "imageQuery": "Earth",
      "musicCategory": "",
      "caption": "Earth is the only planet known to support life!"
    },
    {
      "wordIndex": 14,
      "triggerWord": "Jupiter",
      "type": "both",
      "imageQuery": "Jupiter",
      "musicCategory": "mysterious",
      "caption": "Jupiter is so big, it's like a giant in space!"
    },
    {
      "wordIndex": 24,
      "triggerWord": "thousand",
      "type": "music",
      "imageQuery": "",
      "musicCategory": "adventure",
      "caption": "Imagine filling Jupiter with a thousand Earths, that's a huge adventure!"
    }
  ],
  "3-1": [
    {
      "wordIndex": 7,
      "triggerWord": "make",
      "type": "image",
      "imageQuery": "Pancakes",
      "caption": "Pancakes are a yummy breakfast loved by many kids!"
    },
    {
      "wordIndex": 28,
      "triggerWord": "delicious",
      "type": "music",
      "musicCategory": "celebration",
      "caption": "Delicious food makes everyone want to celebrate with joy!"
    },
    {
      "wordIndex": 33,
      "triggerWord": "maple",
      "type": "both",
      "imageQuery": "Maple_syrup",
      "musicCategory": "peaceful",
      "caption": "Maple syrup is sweet and perfect for pancakes!"
    }
  ],
  "3-2": [
    {
      "wordIndex": 6,
      "triggerWord": "treehouse.",
      "type": "image",
      "imageQuery": "Treehouse",
      "caption": "Treehouses are fun hideouts built high among the branches!"
    },
    {
      "wordIndex": 24,
      "triggerWord": "sitting",
      "type": "music",
      "musicCategory": "peaceful",
      "caption": "Listening to peaceful music makes sitting in a treehouse even better!"
    },
    {
      "wordIndex": 30,
      "triggerWord": "birds.",
      "type": "both",
      "imageQuery": "Birds",
      "musicCategory": "nature",
      "caption": "There are over 10,000 bird species singing all around the world!"
    }
  ],
  "4-0": [
    {
      "wordIndex": 6,
      "triggerWord": "cycle.",
      "type": "image",
      "imageQuery": "Water_cycle",
      "caption": "The water cycle is nature's way of recycling water!"
    },
    {
      "wordIndex": 8,
      "triggerWord": "sun",
      "type": "music",
      "musicCategory": "nature",
      "caption": "The sun helps plants and animals grow every day!"
    },
    {
      "wordIndex": 24,
      "triggerWord": "clouds.",
      "type": "image",
      "imageQuery": "Cloud",
      "caption": "Clouds can take many shapes and look like fluffy cotton candy!"
    },
    {
      "wordIndex": 30,
      "triggerWord": "rain",
      "type": "music",
      "musicCategory": "peaceful",
      "caption": "Rain helps flowers bloom and keeps the Earth green!"
    }
  ],
  "4-1": [
    {
      "wordIndex": 0,
      "triggerWord": "Penguins",
      "type": "image",
      "imageQuery": "Penguin",
      "caption": "Did you know there are 18 different species of penguins?"
    },
    {
      "wordIndex": 12,
      "triggerWord": "Emperor",
      "type": "music",
      "musicCategory": "adventure",
      "caption": "Emperor penguins are the largest of all penguin species!"
    },
    {
      "wordIndex": 16,
      "triggerWord": "Antarctica",
      "type": "both",
      "imageQuery": "Antarctica",
      "musicCategory": "mysterious",
      "caption": "Antarctica is the coldest place on Earth, home to amazing wildlife!"
    },
    {
      "wordIndex": 35,
      "triggerWord": "blizzards.",
      "type": "music",
      "musicCategory": "dramatic",
      "caption": "Blizzards can create snowdrifts that are taller than a house!"
    }
  ],
  "4-2": [
    {
      "wordIndex": 0,
      "triggerWord": "Pizza",
      "type": "image",
      "imageQuery": "Pizza",
      "caption": "Did you know pizza is loved in many countries worldwide?"
    },
    {
      "wordIndex": 12,
      "triggerWord": "Naples",
      "type": "both",
      "imageQuery": "Naples",
      "musicCategory": "adventure",
      "caption": "Naples is famous for its beautiful coast and delicious food!"
    },
    {
      "wordIndex": 30,
      "triggerWord": "Italian",
      "type": "music",
      "musicCategory": "celebration",
      "caption": "Italy is known for its vibrant festivals and fun music!"
    }
  ],
  "5-0": [
    {
      "wordIndex": 1,
      "triggerWord": "Amazon",
      "type": "image",
      "imageQuery": "Amazon_rainforest",
      "musicCategory": "",
      "caption": "The Amazon is home to amazing plants and animals!"
    },
    {
      "wordIndex": 17,
      "triggerWord": "produces",
      "type": "music",
      "imageQuery": "",
      "musicCategory": "nature",
      "caption": "The rainforest helps create fresh air for us to breathe!"
    },
    {
      "wordIndex": 30,
      "triggerWord": "species",
      "type": "both",
      "imageQuery": "Biodiversity",
      "musicCategory": "mysterious",
      "caption": "There are many unknown creatures waiting to be discovered!"
    }
  ],
  "5-1": [
    {
      "wordIndex": 5,
      "triggerWord": "pyramids",
      "type": "image",
      "imageQuery": "Pyramids_of_Giza",
      "caption": "Did you know the pyramids were built as tombs for pharaohs?"
    },
    {
      "wordIndex": 12,
      "triggerWord": "Great",
      "type": "both",
      "imageQuery": "Great_Pyramid_of_Giza",
      "musicCategory": "mysterious",
      "caption": "The Great Pyramid is the largest of all pyramids in Egypt!"
    },
    {
      "wordIndex": 30,
      "triggerWord": "Historians",
      "type": "music",
      "musicCategory": "adventure",
      "caption": "Historians uncover amazing stories about ancient civilizations every day!"
    }
  ],
  "5-2": [
    {
      "wordIndex": 6,
      "triggerWord": "ocean",
      "type": "image",
      "imageQuery": "Ocean",
      "caption": "The ocean is home to countless amazing creatures and hidden wonders!"
    },
    {
      "wordIndex": 13,
      "triggerWord": "Mariana",
      "type": "both",
      "imageQuery": "Mariana_Trench",
      "musicCategory": "mysterious",
      "caption": "The Mariana Trench is the deepest part of our Earth's oceans!"
    },
    {
      "wordIndex": 22,
      "triggerWord": "Remarkable",
      "type": "music",
      "musicCategory": "adventure",
      "caption": "Explore the adventurous world of ocean creatures!"
    },
    {
      "wordIndex": 32,
      "triggerWord": "Scientists",
      "type": "both",
      "imageQuery": "Marine_science",
      "musicCategory": "peaceful",
      "caption": "Scientists help us learn about the wonders of the ocean!"
    }
  ],
  "6-0": [
    {
      "wordIndex": 0,
      "triggerWord": "Photosynthesis",
      "type": "image",
      "imageQuery": "Photosynthesis",
      "musicCategory": "",
      "caption": "Photosynthesis helps plants grow using sunlight!"
    },
    {
      "wordIndex": 12,
      "triggerWord": "Chlorophyll,",
      "type": "image",
      "imageQuery": "Chlorophyll",
      "musicCategory": "",
      "caption": "Chlorophyll gives plants their green color!"
    },
    {
      "wordIndex": 33,
      "triggerWord": "This",
      "type": "music",
      "imageQuery": "",
      "musicCategory": "peaceful",
      "caption": "Relax with peaceful music while we learn about life on Earth."
    },
    {
      "wordIndex": 45,
      "triggerWord": "oxygen",
      "type": "both",
      "imageQuery": "Oxygen",
      "musicCategory": "nature",
      "caption": "Oxygen is essential for us to breathe and live!"
    }
  ],
  "6-1": [
    {
      "wordIndex": 1,
      "triggerWord": "Renaissance",
      "type": "image",
      "imageQuery": "Renaissance_art",
      "caption": "The Renaissance brought amazing art that still inspires us today!"
    },
    {
      "wordIndex": 20,
      "triggerWord": "Leonardo",
      "type": "both",
      "imageQuery": "Leonardo_da_Vinci",
      "musicCategory": "adventure",
      "caption": "Leonardo da Vinci was a brilliant artist and inventor with many cool ideas!"
    },
    {
      "wordIndex": 34,
      "triggerWord": "Galileo",
      "type": "both",
      "imageQuery": "Galileo_Galilei",
      "musicCategory": "mysterious",
      "caption": "Galileo looked at the stars and changed how we see the universe!"
    },
    {
      "wordIndex": 46,
      "triggerWord": "civilization",
      "type": "music",
      "musicCategory": "celebration",
      "caption": "Civilizations have unique stories that are fun to explore and celebrate!"
    }
  ],
  "6-2": [
    {
      "wordIndex": 0,
      "triggerWord": "Artificial",
      "type": "image",
      "imageQuery": "Artificial_intelligence",
      "musicCategory": "",
      "caption": "Artificial intelligence helps computers think like humans!"
    },
    {
      "wordIndex": 33,
      "triggerWord": "healthcare,",
      "type": "both",
      "imageQuery": "Healthcare",
      "musicCategory": "peaceful",
      "caption": "AI can assist doctors in diagnosing illnesses faster!"
    },
    {
      "wordIndex": 34,
      "triggerWord": "education,",
      "type": "both",
      "imageQuery": "Education",
      "musicCategory": "peaceful",
      "caption": "AI helps students learn with personalized lessons!"
    },
    {
      "wordIndex": 36,
      "triggerWord": "transportation,",
      "type": "both",
      "imageQuery": "Transportation",
      "musicCategory": "adventure",
      "caption": "Self-driving cars use AI to navigate safely!"
    }
  ]
};
